### ISSUE TITLE
You have installed version 2.10.8 of Cbc, which is not supported by Cbc.jl

### ISSUE THREAD

**Issue by sklink** [jump-dev/Cbc.jl#210] opened 2022-11-01 15:40 UTC
I have added Cbc via `add Cbc` in Julia REPL. The build works fine on my Mac with M1 but on GitHub Actions and on my Windows PC I receive this error:

```
Failed to precompile MyPackage [e2d255a6-a9f0-4867-97a6-ac6706df2382] to /var/runtime/julia_depot/compiled/v1.8/MyPackage/jl_lkG0IL.
ERROR: LoadError: You have installed version 2.10.8 of Cbc, which is not supported by
Cbc.jl We require Cbc version 2.10. After installing Cbc 2.10, run:

    import Pkg
    Pkg.rm("Cbc")
    Pkg.add("Cbc")

If you have a newer version of Cbc installed, changes may need to be made
to the Julia code. Please open an issue at
https://github.com/jump-dev/Cbc.jl.
```

My understanding is that `Cbc.jl` is the one installing those binaries -- I don't have them pre-installed anywhere.

**Comment by sklink** [comment] 2022-11-01 15:46
Seems rather than committing `Cbc` to the package as a dependency, having it added in the build script grabs the proper binaries -- as the error suggests above, except I had to actually remove it from the `Manifest.toml` through `remove Cbc` beforehand.

**Comment by odow** [comment] 2022-11-01 18:28
Please update your packages. This is fixed in `v1.0.3` of Cbc.jl.

**Comment by sklink** [comment] 2022-11-01 18:51
I only attempted to install `Cbc.jl` yesterday, so I believe it should've defaulted to the latest version. We've moved on to using `HiGHs` instead but I'll give this another shot if we need to switch back.

**Comment by odow** [comment] 2022-11-01 19:02
> We've moved on to using HiGHs

Great!

> I'll give this another shot if we need to switch back.

Closing this issue because as far as I'm aware, this is fixed in the latest version. There may have been some other version incompatibilities going on. Hard to say without knowing the details. Please re-open if you can reproduce in future, and provide the output of `import Pkg; Pkg.status()`.

**Closed by odow** 2022-11-01 19:02 UTC
