### ISSUE TITLE
Approximation error when querying solution

### ISSUE THREAD

**Issue by S-Inako** [jump-dev/Cbc.jl#177] opened 2021-09-30 09:39 UTC
Hi
I've been playing around with MILP and when trying to solve the knapsack problem using Cbc I encountered suboptimal solutions
It may be an error in my code, a parameter which I should have specified or a real issue (maybe I should report it on the Cbc github page, please bear with me I'm new here).

Here is a MWE
```
using JuMP, Cbc, LinearAlgebra

ksv(C, ks) = sum(C[ks]) # return cost of a given solution for specified costs
ksw(A, ks) = sum(A[ks]) # return total weight of a given solution for specified weights

function knapsack_milp(C, A, b)
    m = Model(Cbc.Optimizer)
    n = length(C)
    
    @variable(m, X[1:n], Bin)
    @objective(m, Max, dot(C,X))
    @constraint(m, dot(A,X) <= b)
    
    optimize!(m)
    
    return sort(findall(x->x==1, value.(X)))
end

C = [5, 29, 60, 37, 66]
A = [36, 87, 69, 0, 28]
b = 80.0

sub_optimal = knapsack_milp(C, A, b)
# Found [1, 5], cost : 71, weight : 64

optimal = [1, 4, 5] 
# cost : 108, weight : 64

@assert ksw(A, optimal) <= b

println("Cbc solution value : $(ksv(C, sub_optimal))")
println("Optimal solution value : $(ksv(C, optimal))")
```

JuMP v0.21.10, Cbc v0.8.1

It should be noted that optimal solutions are found using GLPK v0.14.14

Thanks in advance

**Comment by Inakoala** [comment] 2021-09-30 10:02
So this may be a short issue

I was running this code in a Pluto notebook so I didn't see the solver output, which indicates an objective value of 108 (optimal).

The problem is due to numerical approximation I guess, as the solution vector before filtering is `[1.0, 0.0, 0.0, 0.9999999999999999, 1.0]`.

Now as I specified the solution vector to be binary I guessed any approximation made during the resolution would have been corrected when querying the solution (by rounding each variable supposed to be integer).

I wonder if this behaviour is to be expected or not, should I close the issue ?

**Comment by odow** [comment] 2021-09-30 21:05
Closing because this is expected behavior. All solvers (not just Cbc) only find solutions to a tolerance, typically ~1e-6.

Gurobi has a good set of articles if this is new to you:
https://www.gurobi.com/documentation/9.0/refman/num_tolerances_and_user_sc.html

**Closed by odow** 2021-09-30 21:05 UTC
