### ISSUE TITLE
More granular support of SOS1 and SOS2

### ISSUE THREAD

**Issue by ValentinKaisermayer** [jump-dev/Cbc.jl#227] opened 2024-05-03 06:33 UTC
I have some solver-agnostic code where I already check: 
```julia
MOI.supports_constraint(JuMP.backend(model), MOI.VectorOfVariables, MOI.SOS1{Float64})
```
But this does not work here, since `Cbc` does support them.

Why are SOS1 and SOS2 constraints supported 
https://github.com/jump-dev/Cbc.jl/blob/a7ea668ff8d5ef8cd881b85a51ef26c37e8559ea/src/MOI_wrapper/MOI_wrapper.jl#L483-L489

when the solver states
https://github.com/jump-dev/Cbc.jl/blob/a7ea668ff8d5ef8cd881b85a51ef26c37e8559ea/src/MOI_wrapper/MOI_wrapper.jl#L422-L423

Is there a way of not supporting them just for non-binary variables.

**Comment by blegat** [comment] 2024-05-03 06:47
Unfortunately, the way `supports` communicates is constraint-wise so there is no way to communicate that a SOS constraint with non-binary variables is not supported. The only way would be to have different sets for SOS constraints with binary and non-binary. Alternatively, Cbc could also correctly handle these cases

**Comment by odow** [comment] 2024-05-03 07:15
> Is there a way of not supporting them just for non-binary variables.

No. Just don't use Cbc. Use HiGHS instead.

**Comment by odow** [comment] 2024-05-03 23:44
Closing as a duplicate of #151. I don't want to complicate MOI by adding more complexity to how we manage `supports_constraint`. 

Our options are:

 * Do nothing.
 * Build and distribute un-released `master` version of Cbc and required dependencies
 * Do something like adding a binary variable to the end of each SOS constraint.

**Closed by odow** 2024-05-03 23:44 UTC
